version: '2'

services:

  db:
    image: mongo

  web:
    image: node:7.7.4
    volumes:
      - ./:/root/shortener-js
    working_dir: /root/shortener-js
    restart: always
    tty: true
    ports:
      - "8888:8888"
    links: 
      - db
  