version: '2'

services:

  db:
    image: mongo

  web:
    build: .
    volumes:
      - ./:/root/shortner-js
      - /root/shortener-js/node_modules
    working_dir: /root/shortner-js
    restart: always
    tty: true
    ports:
      - "8888:8888"
    links: 
      - db
  